sudo: required
services:
  - docker

before_install:
  - docker build -t devraghavm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true devraghavm/react-test npm test

after_success:
  - docker build -t devraghavm/multi-client ./client
  - docker build -t devraghavm/multi-nginx ./nginx
  - docker build -t devraghavm/multi-server ./server
  - docker build -t devraghavm/multi-worker ./worker
  # Log In to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to dockerhub
  - docker push devraghavm/multi-client
  - docker push devraghavm/multi-nginx
  - docker push devraghavm/multi-server
  - docker push devraghavm/multi-worker
